version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./nestjs
      target: development
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/pong_game/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./nestjs/conf:/pong_game/src/app
      - /pong_game/src/app/node_modules/
    # RUN in debug mode: npm run start:debug -> Also start your vscode debugger
    # RUN in dev mode: npm run start:dev
    # RUN in production mode: npm run start:prod
    command: npm run start:debug
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
      - 9229:9229
    container_name: ponggame_api

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./vue
      target: development
    volumes:
      - ./vue/conf:/pong_game/frontend/src/app
      - /pong_game/frontend/src/app/node_modules/
    # RUN in dev mode: npm run start:dev
    # RUN in preview mode: npm run start:preview
    command: npm run dev
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 4200:4200
    links:
      - api
    container_name: ponggame_frontend

  postgres:
    build:
      dockerfile: Dockerfile
      context: ./postgres
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 35000:5432
    container_name: ponggame_postgres

  adminer:
    build:
      dockerfile: Dockerfile
      context: ./adminer
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 5050:80
    container_name: ponggame_adminer
